### PR TITLE
Enhance GStreamer Detection App with GUI and Improved Reliability

### PR DESCRIPTION
**Pull request by chm10**
Alternative #40 has more changes and can break other codes. Need someone test another all functionality is ok. 

- Implement Gtk-based GUI for video display
- Add watchdog mechanism to monitor and restart pipeline if needed
- Improve RTSP connection handling with retry mechanism
- Implement logging for better debugging and monitoring
- Refactor pipeline creation and management for better modularity
- Add error handling and graceful shutdown procedures
- Optimize video processing with threading and improved buffer management
- Enhance user interface with custom drawing area for video display
- Implement window close event handling for proper application shutdown

Disclaimer:
I am not the owner or maintainer of this project. This pull request is a suggested solution based on
the information available in issue https://github.com/hailo-ai/hailo-rpi5-examples/issues/39. It is provided "as is", without warranty of any kind, express
or implied. The project maintainers should review and test these changes thoroughly before considering
implementation. I'm open to feedback and further modifications if needed.

### CODE REVIEW

**Comment by giladnah** [comment]
@chm10  This is excellent work that I would be happy to merge. After running your code, I now understand what you meant by 'video hangs'—this happens when the file reaches the end, right?

I can't merge your code as-is because many of the remarks were removed, and I believe the correct place for your added functionality is in the GStreamerApp class in hailo_rpi_common.py. This way, all applications can benefit from it.

Please let me know if you'd like to make these changes yourself (and get your code merged with our extreme gratitude), or if you'd prefer us to handle it.

Once again, your contribution is highly appreciated.

**Comment by giladnah** [comment]
Note that the initial video window remains open and you open a new one after restarting the pipeline.

**Comment by giladnah** [comment]
@chm10 this code runs on X86 but not on the RPi because it uses wayland not x11

**Comment by chm10** [comment]
Yes, I use ssh access from x86 I mentioned in the issue.

**Comment by giladnah** [comment]
I've added a 'rewind' feature in the new release. This should cover the video issues. Regarding GUI we must support all platforms. I'd be very happy to see you UI as a community project, you can publish it in our community.

**Pull request closed without merging**
